/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import db.DBManager.Record;
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author tonitan
 */
public class AddAdvFrame extends javax.swing.JFrame {

    /**
     * Creates new form add_adv
     */
    DBManager DB;
    String user_id;
    UserFrame parent;
    
    public AddAdvFrame(UserFrame parent,DBManager DB, String user_id) {
        this.setTitle("Add Adv Frame");
        this.parent=parent;
        this.DB=DB;
        this.user_id=user_id;
        initComponents();
        populate_category_type();
    }

    private void populate_category_type(){
        LinkedList<Record>category_types=DB.getCategoryTypes();
        this.category_combo.removeAllItems();
        for(Record category_type:category_types){
            this.category_combo.addItem(category_type.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        title_box = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        category_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        price_box = new javax.swing.JTextField();
        add_adv_button = new javax.swing.JButton();
        details_box = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Title:");

        title_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_boxActionPerformed(evt);
            }
        });

        jLabel2.setText("Details:");

        jLabel3.setText("Category:");

        category_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAT", "HOU", "ELC", "CCA" }));
        category_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_comboActionPerformed(evt);
            }
        });

        jLabel4.setText("Price:");

        price_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_boxActionPerformed(evt);
            }
        });

        add_adv_button.setText("Add Advertisement");
        add_adv_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_adv_buttonActionPerformed(evt);
            }
        });

        details_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                details_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_adv_button, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(title_box)
                    .addComponent(category_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price_box)
                    .addComponent(details_box))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(title_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(details_box, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(price_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(add_adv_button)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void price_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_boxActionPerformed

    private void title_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_boxActionPerformed

    private void category_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_comboActionPerformed

    private void details_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_details_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_details_boxActionPerformed

    private void add_adv_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_adv_buttonActionPerformed
        // TODO add your handling code here:
        String adv_title=this.title_box.getText();
        String adv_description=this.details_box.getText();
        String adv_price=this.price_box.getText();
        String cat_id=((Record)this.category_combo.getSelectedItem()).ID;
        if(adv_title.trim().equals("")){
            JOptionPane.showMessageDialog(this,"New Adv was added correctly","Confirmation",JOptionPane.ERROR_MESSAGE);
          return;
        }
        boolean result=DB.addAdv(adv_title,adv_description,adv_price,cat_id,user_id);
                if(result){
             JOptionPane.showMessageDialog(this,
    "A new adv was added correctly",
    "Confirmation",
    JOptionPane.INFORMATION_MESSAGE);
             parent.populate_user_adv_table();
        }
        
    }//GEN-LAST:event_add_adv_buttonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_adv_button;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JTextField details_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField price_box;
    private javax.swing.JTextField title_box;
    // End of variables declaration//GEN-END:variables
}
